#include <semu/core/capability.hpp>

#include <cstdio>

#include "capability_data.hpp"

namespace semu {

const char* to_string(CapabilityState state) {
    switch (state) {
        case CapabilityState::kDecodeOnly: return "decode-only";
        case CapabilityState::kFunctional: return "functional";
        case CapabilityState::kProfiled: return "profiled";
        case CapabilityState::kUnsupported: return "unsupported";
    }
    return "unsupported";
}

std::optional<CapabilityState> parse_capability_state(std::string_view name) {
    if (name == "decode-only") return CapabilityState::kDecodeOnly;
    if (name == "functional") return CapabilityState::kFunctional;
    if (name == "profiled") return CapabilityState::kProfiled;
    if (name == "unsupported") return CapabilityState::kUnsupported;
    return std::nullopt;
}

const CapabilityManifest& CapabilityManifest::current() {
    static const CapabilityManifest inst = [] {
        const auto& g = generated::kCapabilityManifest;
        CapabilityManifest m;
        auto& h = m.header_;
        h.manifest_version = g.manifest_version;
        h.generator = g.generator;
        h.generated_from = g.generated_from;
        h.arch = g.arch;
        h.variants = g.variants;
        h.mnemonics = g.mnemonics;
        h.enums = g.enums;
        h.tables = g.tables;
        h.funit_fields = g.funit_fields;
        h.pipes = g.pipes;
        h.reference_platform = g.reference_platform;
        h.baseline_corpus = g.baseline_corpus;
        m.entries_.reserve(static_cast<std::size_t>(g.num_rows));
        for (int i = 0; i < g.num_rows; ++i) {
            const auto& r = g.rows[i];
            CapabilityEntry e;
            e.mnemonic = r.mnemonic;
            e.variant_class = r.variant_class;
            e.opcode = r.opcode;
            e.pipe = r.pipe;
            e.state = r.state;
            e.note = r.note;
            m.entries_.push_back(std::move(e));
        }
        return m;
    }();
    return inst;
}

std::vector<const CapabilityEntry*> CapabilityManifest::by_mnemonic(
    std::string_view mnemonic) const {
    std::vector<const CapabilityEntry*> out;
    for (const auto& e : entries_) {
        if (e.mnemonic == mnemonic) out.push_back(&e);
    }
    return out;
}

std::vector<const CapabilityEntry*> CapabilityManifest::by_opcode(
    std::uint16_t opcode) const {
    std::vector<const CapabilityEntry*> out;
    for (const auto& e : entries_) {
        if (e.opcode == opcode) out.push_back(&e);
    }
    return out;
}

std::size_t CapabilityManifest::count(CapabilityState state) const {
    std::size_t n = 0;
    for (const auto& e : entries_) {
        if (e.state == state) ++n;
    }
    return n;
}

std::string CapabilityManifest::to_text(bool full) const {
    std::string out;
    char buf[512];

    std::snprintf(buf, sizeof(buf),
                  "semu capability manifest v%d (arch %s)\n",
                  header_.manifest_version, header_.arch.c_str());
    out += buf;
    std::snprintf(buf, sizeof(buf), "  generated by: %s\n",
                  header_.generator.c_str());
    out += buf;
    std::snprintf(buf, sizeof(buf), "  generated from: %s\n",
                  header_.generated_from.c_str());
    out += buf;
    std::snprintf(buf, sizeof(buf),
                  "  sm120 data scale: %d variants / %d mnemonics / %d enums / "
                  "%d tables / %d funit fields / %d pipes\n",
                  header_.variants, header_.mnemonics, header_.enums,
                  header_.tables, header_.funit_fields, header_.pipes);
    out += buf;
    std::snprintf(buf, sizeof(buf), "  reference platform: %s\n",
                  header_.reference_platform.c_str());
    out += buf;
    std::snprintf(buf, sizeof(buf), "  baseline corpus: %s\n",
                  header_.baseline_corpus.c_str());
    out += buf;
    std::snprintf(buf, sizeof(buf),
                  "  capability counts: decode-only %zu / functional %zu / "
                  "profiled %zu / unsupported %zu\n",
                  count(CapabilityState::kDecodeOnly),
                  count(CapabilityState::kFunctional),
                  count(CapabilityState::kProfiled),
                  count(CapabilityState::kUnsupported));
    out += buf;

    if (full) {
        out += "  rows (mnemonic, variant_class, opcode, pipe, state, note):\n";
        for (const auto& e : entries_) {
            std::snprintf(buf, sizeof(buf), "    %s %s %u %s %s %s\n",
                          e.mnemonic.c_str(), e.variant_class.c_str(), e.opcode,
                          e.pipe.c_str(), to_string(e.state), e.note.c_str());
            out += buf;
        }
    }
    return out;
}

namespace {

// Minimal deterministic JSON writer/reader for the manifest.  Kept stdlib-only;
// field order is fixed so serialization round-trips byte-identically.

std::string json_escape(const std::string& s) {
    std::string out;
    out.reserve(s.size() + 8);
    for (char c : s) {
        switch (c) {
            case '"': out += "\\\""; break;
            case '\\': out += "\\\\"; break;
            case '\n': out += "\\n"; break;
            case '\r': out += "\\r"; break;
            case '\t': out += "\\t"; break;
            default:
                if (static_cast<unsigned char>(c) < 0x20) {
                    char buf[8];
                    std::snprintf(buf, sizeof(buf), "\\u%04x", c);
                    out += buf;
                } else {
                    out += c;
                }
        }
    }
    return out;
}

struct JsonParser {
    std::string_view s;
    std::size_t i = 0;

    void skip_ws() {
        while (i < s.size() &&
               (s[i] == ' ' || s[i] == '\n' || s[i] == '\t' || s[i] == '\r')) {
            ++i;
        }
    }
    bool eof() const { return i >= s.size(); }
    bool consume(char c) {
        skip_ws();
        if (i < s.size() && s[i] == c) {
            ++i;
            return true;
        }
        return false;
    }
    std::string parse_string() {
        skip_ws();
        if (i >= s.size() || s[i] != '"') return {};
        ++i;
        std::string out;
        while (i < s.size()) {
            char c = s[i++];
            if (c == '"') break;
            if (c == '\\' && i < s.size()) {
                char e = s[i++];
                switch (e) {
                    case '"': out += '"'; break;
                    case '\\': out += '\\'; break;
                    case 'n': out += '\n'; break;
                    case 'r': out += '\r'; break;
                    case 't': out += '\t'; break;
                    default: out += e;
                }
            } else {
                out += c;
            }
        }
        return out;
    }
    std::int64_t parse_int() {
        skip_ws();
        bool neg = false;
        if (i < s.size() && s[i] == '-') {
            neg = true;
            ++i;
        }
        std::int64_t v = 0;
        while (i < s.size() && s[i] >= '0' && s[i] <= '9') {
            v = v * 10 + (s[i] - '0');
            ++i;
        }
        return neg ? -v : v;
    }
};

}  // namespace

std::string CapabilityManifest::to_json() const {
    std::string out = "{\n";
    char buf[128];
    const auto h = header_;
    out += "  \"manifest_version\": " +
           std::to_string(h.manifest_version) + ",\n";
    out += "  \"generator\": \"" + json_escape(h.generator) + "\",\n";
    out += "  \"generated_from\": \"" + json_escape(h.generated_from) + "\",\n";
    out += "  \"arch\": \"" + json_escape(h.arch) + "\",\n";
    std::snprintf(buf, sizeof(buf),
                  "  \"variants\": %d,\n  \"mnemonics\": %d,\n  \"enums\": %d,\n"
                  "  \"tables\": %d,\n  \"funit_fields\": %d,\n  \"pipes\": %d,\n",
                  h.variants, h.mnemonics, h.enums, h.tables, h.funit_fields,
                  h.pipes);
    out += buf;
    out += "  \"reference_platform\": \"" + json_escape(h.reference_platform) +
           "\",\n";
    out += "  \"baseline_corpus\": \"" + json_escape(h.baseline_corpus) +
           "\",\n";
    out += "  \"rows\": [\n";
    for (std::size_t k = 0; k < entries_.size(); ++k) {
        const auto& e = entries_[k];
        out += "    {\"mnemonic\": \"" + json_escape(e.mnemonic) +
               "\", \"variant_class\": \"" + json_escape(e.variant_class) +
               "\", \"opcode\": " + std::to_string(e.opcode) + ", \"pipe\": \"" +
               json_escape(e.pipe) + "\", \"state\": \"" +
               to_string(e.state) + "\", \"note\": \"" + json_escape(e.note) +
               "\"}";
        out += (k + 1 < entries_.size()) ? ",\n" : "\n";
    }
    out += "  ]\n}\n";
    return out;
}

std::optional<CapabilityManifest> CapabilityManifest::from_json(
    std::string_view json) {
    JsonParser p{json};
    CapabilityManifest m;
    auto& h = m.header_;

    if (!p.consume('{')) return std::nullopt;
    while (true) {
        p.consume(',');  // optional separator
        if (p.consume('}')) break;
        std::string key = p.parse_string();
        if (!p.consume(':')) return std::nullopt;
        if (key == "manifest_version") {
            h.manifest_version = static_cast<int>(p.parse_int());
        } else if (key == "generator") {
            h.generator = p.parse_string();
        } else if (key == "generated_from") {
            h.generated_from = p.parse_string();
        } else if (key == "arch") {
            h.arch = p.parse_string();
        } else if (key == "variants") {
            h.variants = static_cast<int>(p.parse_int());
        } else if (key == "mnemonics") {
            h.mnemonics = static_cast<int>(p.parse_int());
        } else if (key == "enums") {
            h.enums = static_cast<int>(p.parse_int());
        } else if (key == "tables") {
            h.tables = static_cast<int>(p.parse_int());
        } else if (key == "funit_fields") {
            h.funit_fields = static_cast<int>(p.parse_int());
        } else if (key == "pipes") {
            h.pipes = static_cast<int>(p.parse_int());
        } else if (key == "reference_platform") {
            h.reference_platform = p.parse_string();
        } else if (key == "baseline_corpus") {
            h.baseline_corpus = p.parse_string();
        } else if (key == "rows") {
            if (!p.consume('[')) return std::nullopt;
            while (true) {
                p.consume(',');  // optional separator
                if (p.consume(']')) break;
                if (!p.consume('{')) return std::nullopt;
                CapabilityEntry e;
                while (true) {
                    p.consume(',');  // optional separator
                    if (p.consume('}')) break;
                    std::string rk = p.parse_string();
                    if (!p.consume(':')) return std::nullopt;
                    if (rk == "mnemonic") {
                        e.mnemonic = p.parse_string();
                    } else if (rk == "variant_class") {
                        e.variant_class = p.parse_string();
                    } else if (rk == "opcode") {
                        e.opcode = static_cast<std::uint16_t>(p.parse_int());
                    } else if (rk == "pipe") {
                        e.pipe = p.parse_string();
                    } else if (rk == "state") {
                        auto st = parse_capability_state(p.parse_string());
                        if (!st) return std::nullopt;
                        e.state = *st;
                    } else if (rk == "note") {
                        e.note = p.parse_string();
                    }
                }
                m.entries_.push_back(std::move(e));
            }
        } else {
            // Unknown key: skip its scalar value.
            if (p.consume('{')) {
                while (!p.consume('}')) p.parse_string();
            } else if (p.consume('[')) {
                while (!p.consume(']')) p.parse_string();
            } else {
                p.parse_string();
            }
        }
    }
    return m;
}

}  // namespace semu
