"""Architecture configuration for the SASS assembler.

Each supported GPU arch (sm90 Hopper, sm120 Blackwell) has:
  db            — the parsed ISA JSON DB (generated by tools/parse_sm90.py or
                  tools/parse_sm120.py) used by matcher/encoder;
  default_cdesc — the const-bank slot where the driver plants the default
                  global cache descriptor (sm90: c[0x0][0x208], verified on
                  H800; sm120: c[0x0][0x358], verified on RTX 5090);
  param_base    — the const-bank offset where the driver places kernel
                  parameters (sm90: 0x210; sm120: 0x380).

The process keeps a current arch (default sm120, matching the historical
behaviour).  Top-level entry points (``assemble``/``assemble_kernel``/
``assemble_flat``) accept ``arch=`` and temporarily switch for that call;
``set_arch`` changes the process-wide default (used by run_tests / scripts).
"""

from __future__ import annotations
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class ArchConfig:
    name: str
    db: str
    default_cdesc: tuple            # (bank, offset)
    param_base: int


ARCHES: dict[str, ArchConfig] = {
    "sm90": ArchConfig("sm90", "sm90.json", (0, 0x208), 0x210),
    "sm120": ArchConfig("sm120", "sm120.json", (0, 0x358), 0x380),
}
DEFAULT_ARCH = "sm120"

_active: str = DEFAULT_ARCH


def current() -> ArchConfig:
    return ARCHES[_active]


def set_arch(name: str) -> None:
    global _active
    if name not in ARCHES:
        raise ValueError(f"unknown arch {name!r} (choose from {sorted(ARCHES)})")
    _active = name


def db_path(name: str | None = None) -> Path:
    cfg = ARCHES[name] if name is not None else current()
    return Path(__file__).resolve().parent.parent / cfg.db


def spec_const_map() -> dict:
    """#spec_const(NAME) → const-bank slot for the current arch."""
    return {"SLOT_DEFAULT_CDESC": current().default_cdesc}
